version: "3.1"

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
    links:
      - php

  php:
    build: ./docker/php
    volumes:
      - ./:/app
    environment:
      - XDEBUG_CONFIG=remote_host=host.docker.internal
      - DATABASE_HOST=mariadb
      - DATABASE_USER=pachinko
      - DATABASE_PASSWORD=pachinko
    links:
      - mariadb

  mariadb:
    image: mariadb:latest
    ports:
      - "3307:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
      - ./pachinko.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      - MYSQL_DATABASE=pachinko
      - MYSQL_USER=pachinko
      - MYSQL_PASSWORD=pachinko
      - MYSQL_ROOT_PASSWORD=root
