version: "3.1"

services:
  nginx:
    image: nginx:1.23
    ports:
      - "8080:80"
    volumes:
      - ./:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  php:
    build: ./docker/php
    volumes:
      - ./:/app
    environment:
      - DATABASE_URL=mysql:host=localhost;dbname=pachinko;charset=utf8mb4;user=pachinko;password=pachinko
    links:
      - mariadb

  mariadb:
    image: mariadb:10.7
    volumes:
      - ./pachinko.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      - MYSQL_DATABASE=pachinko
      - MYSQL_USER=pachinko
      - MYSQL_PASSWORD=pachinko
      - MYSQL_ROOT_PASSWORD=root
