# fly.toml app configuration file generated for pachinko on 2023-08-14T15:08:02+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pachinko"
primary_region = "cdg"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 0
  processes = ["app"]
